[package]
name = "exercise4"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "exercise4"
path = "src/exercise4.rs"

[dependencies]
semaphore = "0.4.0"
